using System.Text.Json.Nodes;

namespace Civil3DMcpPlugin;

public static class CommandDispatcher
{
  public static Task<object?> DispatchAsync(string method, JsonObject? parameters, CancellationToken cancellationToken)
  {
  return method switch
  {
      "getCivil3DHealth" => DrawingCommands.GetCivil3DHealthAsync(),
      "createCircle" => DrawingCommands.CreateCircleAsync(parameters),
      "getDrawingInfo" => DrawingCommands.GetDrawingInfoAsync(),
      "getProjectContext" => DrawingCommands.GetProjectContextAsync(parameters),
      "getDrawingSettings" => DrawingCommands.GetDrawingSettingsAsync(),
      "getCoordinateSystemInfo" => CoordinateSystemCommands.GetCoordinateSystemInfoAsync(),
      "transformCoordinates" => CoordinateSystemCommands.TransformCoordinatesAsync(parameters),
      "corridorQcReportWorkflow" => WorkflowCommands.CorridorQcReportWorkflowAsync(parameters),
      "surfaceComparisonReportWorkflow" => WorkflowCommands.SurfaceComparisonReportWorkflowAsync(parameters),
      "dataShortcutPublishSyncWorkflow" => WorkflowCommands.DataShortcutPublishSyncWorkflowAsync(parameters),
      "dataShortcutReferenceSyncWorkflow" => WorkflowCommands.DataShortcutReferenceSyncWorkflowAsync(parameters),
      "projectStartupWorkflow" => WorkflowCommands.ProjectStartupWorkflowAsync(parameters),
      "projectReferenceSetupWorkflow" => WorkflowCommands.ProjectReferenceSetupWorkflowAsync(parameters),
      "drawingReadinessAuditWorkflow" => WorkflowCommands.DrawingReadinessAuditWorkflowAsync(parameters),
      "featureLineToGradingWorkflow" => WorkflowCommands.FeatureLineToGradingWorkflowAsync(parameters),
      "planProductionPublishWorkflow" => WorkflowCommands.PlanProductionPublishWorkflowAsync(parameters),
      "qcFixAndVerifyWorkflow" => WorkflowCommands.QcFixAndVerifyWorkflowAsync(parameters),
      "newDrawing" => DrawingCommands.NewDrawingAsync(parameters),
      "saveDrawing" => DrawingCommands.SaveDrawingAsync(parameters),
      "openDrawing" => DrawingCommands.OpenDrawingAsync(parameters),   // 2026-08-13: 打开已有图纸（半自动化工作流）
      "undoDrawing" => DrawingCommands.UndoDrawingAsync(parameters),
      "redoDrawing" => DrawingCommands.RedoDrawingAsync(parameters),
      "createPolyline" => AcadCommands.CreatePolylineAsync(parameters),
      "createText" => AcadCommands.CreateTextAsync(parameters),
      "create3dPolyline" => AcadCommands.Create3dPolylineAsync(parameters),
    "createBox" => AcadCommands.CreateBoxAsync(parameters),
    "createCylinder" => AcadCommands.CreateCylinderAsync(parameters),
    "createSphere" => AcadCommands.CreateSphereAsync(parameters),
    "createCone" => AcadCommands.CreateConeAsync(parameters),
    "createWedge" => AcadCommands.CreateWedgeAsync(parameters),
    "createTorus" => AcadCommands.CreateTorusAsync(parameters),
    
      "createMText" => AcadCommands.CreateMTextAsync(parameters),
      "createLineSegment" => AcadCommands.CreateLineSegmentAsync(parameters),
      "saveSelection" => AcadCommands.SaveSelectionAsync(parameters),
      "listSelectedTexts" => DrawingCommands.ListSelectedTextsAsync(),
      "listTexts" => DrawingCommands.ListTextsAsync(parameters),
      "listCivilObjectTypes" => DrawingCommands.ListCivilObjectTypesAsync(),
      "getSelectedCivilObjectsInfo" => DrawingCommands.GetSelectedCivilObjectsInfoAsync(parameters),
      "getJobStatus" => Task.FromResult<object?>(JobCommands.GetJobStatus(parameters)),
      "cancelJob" => Task.FromResult<object?>(JobCommands.CancelJob(parameters)),
      "startJob" => JobCommands.StartJobAsync(parameters),
      "listCogoPoints" => PointCommands.ListCogoPointsAsync(parameters),
      "getCogoPoint" => PointCommands.GetCogoPointAsync(parameters),
      "createCogoPoints" => PointCommands.CreateCogoPointsAsync(parameters),
      "listPointGroups" => PointCommands.ListPointGroupsAsync(),
      "importCogoPoints" => PointCommands.ImportCogoPointsAsync(parameters),
      "importCogoPointsFromFile" => PointCommands.ImportCogoPointsFromFileAsync(parameters),  // 2026-08-07: 文件通道
      "deleteCogoPoints" => PointCommands.DeleteCogoPointsAsync(parameters),
      "listAlignments" => AlignmentCommands.ListAlignmentsAsync(),
      "getAlignment" => AlignmentCommands.GetAlignmentAsync(parameters),
      "alignmentStationToPoint" => AlignmentCommands.StationToPointAsync(parameters),
      "alignmentSampleStations" => AlignmentCommands.SampleStationsAsync(parameters),
      "alignmentPointToStation" => AlignmentCommands.PointToStationAsync(parameters),
      "createAlignment" => AlignmentCommands.CreateAlignmentAsync(parameters),
      "deleteAlignment" => AlignmentCommands.DeleteAlignmentAsync(parameters),
      "listProfiles" => ProfileCommands.ListProfilesAsync(parameters),
      "getProfile" => ProfileCommands.GetProfileAsync(parameters),
      "getProfileElevation" => ProfileCommands.GetProfileElevationAsync(parameters),
      "sampleProfileElevations" => ProfileCommands.SampleProfileElevationsAsync(parameters),
      "createProfileFromSurface" => ProfileCommands.CreateProfileFromSurfaceAsync(parameters),
      "createLayoutProfile" => ProfileCommands.CreateLayoutProfileAsync(parameters),
      "deleteProfile" => ProfileCommands.DeleteProfileAsync(parameters),
      "listSurfaces" => SurfaceCommands.ListSurfacesAsync(),
      "getSurface" => SurfaceCommands.GetSurfaceAsync(parameters),
      "getSurfaceElevation" => SurfaceCommands.GetSurfaceElevationAsync(parameters),
      "getSurfaceElevationsAlong" => SurfaceCommands.GetSurfaceElevationsAlongAsync(parameters),
      "getSurfaceStatistics" => SurfaceCommands.GetSurfaceStatisticsAsync(parameters),
      "listAssemblies" => AssemblyCreationCommands.ListAssembliesAsync(),
      "listStockSubassemblies" => AssemblyCreationCommands.ListStockSubassembliesAsync(parameters),
      "importSACSubassembly" => AssemblyCreationCommands.ImportSACSubassemblyAsync(parameters),
      "createCustomSubassembly" => AssemblyCreationCommands.CreateCustomSubassemblyAsync(parameters),
      "buildSACSubassembly" => AssemblyCreationCommands.BuildSACSubassemblyAsync(parameters),
      "getAssembly" => AssemblyCreationCommands.GetAssemblyAsync(parameters),
    "getSubassemblyGeometry" => AssemblyCreationCommands.GetSubassemblyGeometryAsync(parameters),
      "verifyAssemblyGeometry" => AssemblyCreationCommands.VerifyAssemblyGeometryAsync(parameters),
      "createSurface" => SurfaceCommands.CreateSurfaceAsync(parameters),
      "deleteSurface" => SurfaceCommands.DeleteSurfaceAsync(parameters),
      "addSurfacePoints" => SurfaceCommands.AddSurfacePointsAsync(parameters),
      "addSurfacePointsFromFile" => SurfaceCommands.AddSurfacePointsFromFileAsync(parameters),  // 2026-08-07: 文件通道(参数化: delimiter/hasHeader/列序)
      "addSurfaceBreakline" => SurfaceCommands.AddSurfaceBreaklineAsync(parameters),
      "addSurfaceBoundary" => SurfaceCommands.AddSurfaceBoundaryAsync(parameters),
      "extractSurfaceContours" => SurfaceCommands.ExtractSurfaceContoursAsync(parameters),
      "computeSurfaceVolume" => SurfaceCommands.ComputeSurfaceVolumeAsync(parameters),
      "addSurfaceWatershed" => SurfaceCommands.AddSurfaceWatershedsAsync(parameters),
      "addSurfaceWatersheds" => SurfaceCommands.AddSurfaceWatershedsAsync(parameters),
      "calculateSurfaceVolume" => SurfaceCommands.CalculateSurfaceVolumeAsync(parameters),
      "getSurfaceVolumeReport" => SurfaceCommands.GetSurfaceVolumeReportAsync(parameters),
      "calculateSurfaceVolumeByRegion" => SurfaceCommands.CalculateSurfaceVolumeByRegionAsync(parameters),
      "analyzeSurfaceSlope" => SurfaceCommands.AnalyzeSurfaceSlopeAsync(parameters),
      "analyzeSurfaceElevation" => SurfaceCommands.AnalyzeSurfaceElevationAsync(parameters),
      "analyzeSurfaceDirections" => SurfaceCommands.AnalyzeSurfaceDirectionsAsync(parameters),
      "setSurfaceContourInterval" => SurfaceCommands.SetSurfaceContourIntervalAsync(parameters),
      "getSurfaceStatisticsDetailed" => SurfaceCommands.GetSurfaceStatisticsDetailedAsync(parameters),
      "sampleSurfaceElevations" => SurfaceCommands.SampleSurfaceElevationsAsync(parameters),
      "createSurfaceFromDem" => SurfaceCommands.CreateSurfaceFromDemAsync(parameters),
      "listSampleLineGroups" => SectionCommands.ListSampleLineGroupsAsync(parameters),
      "getSectionData" => SectionCommands.GetSectionDataAsync(parameters),
      "createSampleLines" => SectionCommands.CreateSampleLinesAsync(parameters),
      "createSectionViews" => SectionCommands.CreateSectionViewsAsync(parameters),
      "listSectionViews" => SectionCommands.ListSectionViewsAsync(parameters),
      "updateSectionViewStyles" => SectionCommands.UpdateSectionViewStylesAsync(parameters),
      "createSectionViewGroup" => SectionCommands.CreateSectionViewGroupAsync(parameters),
      "exportSectionData" => SectionCommands.ExportSectionDataAsync(parameters),
      // Parcels
      "createParcel" => ParcelEditingCommands.CreateParcelAsync(parameters),
      "editParcel" => ParcelEditingCommands.EditParcelAsync(parameters),
      "adjustParcelLotLine" => ParcelEditingCommands.AdjustParcelLotLineAsync(parameters),
      "reportParcels" => ParcelEditingCommands.ReportParcelsAsync(parameters),
      "listHydrologyCapabilities" => HydrologyCommands.ListHydrologyCapabilitiesAsync(),
      "traceHydrologyFlowPath" => HydrologyCommands.TraceFlowPathAsync(parameters),
      "findHydrologyLowPoint" => HydrologyCommands.FindLowPointAsync(parameters),
      "estimateHydrologyRunoff" => HydrologyCommands.EstimateRunoffAsync(parameters),
      "delineateWatershed" => HydrologyCommands.DelineateWatershedAsync(parameters),
      "calculateCatchmentArea" => HydrologyCommands.CalculateCatchmentAreaAsync(parameters),
      "watershedRunoffWorkflow" => HydrologyCommands.WatershedRunoffWorkflowAsync(parameters),
      "runoffDetentionWorkflow" => HydrologyCommands.RunoffDetentionWorkflowAsync(parameters),
      "runoffPipeWorkflow" => HydrologyCommands.RunoffPipeWorkflowAsync(parameters),
      "listCorridors" => CorridorCommands.ListCorridorsAsync(),
      "getCorridor" => CorridorCommands.GetCorridorAsync(parameters),
      "rebuildCorridor" => CorridorCommands.RebuildCorridorAsync(parameters),
      "getCorridorSurfaces" => CorridorCommands.GetCorridorSurfacesAsync(parameters),
      "getCorridorFeatureLines" => CorridorCommands.GetCorridorFeatureLinesAsync(parameters),
      "computeCorridorVolumes" => CorridorCommands.ComputeCorridorVolumesAsync(parameters),
      "getCorridorTargetMappings" => CorridorEditingCommands.GetCorridorTargetMappingsAsync(parameters),
      "setCorridorTargetMappings" => CorridorEditingCommands.SetCorridorTargetMappingsAsync(parameters),
      "addCorridorRegion" => CorridorEditingCommands.AddCorridorRegionAsync(parameters),
      "createCorridor" => CorridorEditingCommands.CreateCorridorAsync(parameters),
      "addCorridorSurface" => CorridorEditingCommands.AddCorridorSurfaceAsync(parameters),   // 2026-09-11: 一键给廊道加曲面
      "deleteCorridorRegion" => CorridorEditingCommands.DeleteCorridorRegionAsync(parameters),
      "listIntersections" => IntersectionCommands.ListIntersectionsAsync(parameters),
      "createIntersection" => IntersectionCommands.CreateIntersectionAsync(parameters),
      "getIntersection" => IntersectionCommands.GetIntersectionAsync(parameters),
      "listParcels" => ParcelEditingCommands.ListParcelsAsync(parameters),
      "getParcel" => ParcelEditingCommands.GetParcelAsync(parameters),
      "listParcelSites" => ParcelEditingCommands.ListParcelSitesAsync(),
      // Pipe networks (gravity)
      "listPipeNetworks" => PipeNetworkCommands.ListPipeNetworksAsync(),
      "getPipeNetwork" => PipeNetworkCommands.GetPipeNetworkAsync(parameters),
      "getPipe" => PipeNetworkCommands.GetPipeAsync(parameters),
      "getStructure" => PipeNetworkCommands.GetStructureAsync(parameters),
      "checkPipeNetworkInterference" => PipeNetworkCommands.CheckPipeNetworkInterferenceAsync(parameters),
      "createPipeNetwork" => PipeNetworkCommands.CreatePipeNetworkAsync(parameters),
      "addPipeToNetwork" => PipeNetworkCommands.AddPipeToNetworkAsync(parameters),
      "resizePipeInNetwork" => PipeNetworkCommands.ResizePipeInNetworkAsync(parameters),
      "addStructureToNetwork" => PipeNetworkCommands.AddStructureToNetworkAsync(parameters),
      "listPipePartsCatalog" => PipeNetworkCommands.ListPipePartsCatalogAsync(parameters),
      "listPressureNetworks" => PressureNetworkCommands.ListPressureNetworksAsync(),
      "getPressureNetworkInfo" => PressureNetworkCommands.GetPressureNetworkInfoAsync(parameters),
      "createPressureNetwork" => PressureNetworkCommands.CreatePressureNetworkAsync(parameters),
      "deletePressureNetwork" => PressureNetworkCommands.DeletePressureNetworkAsync(parameters),
      "assignPressurePartsList" => PressureNetworkCommands.AssignPressurePartsListAsync(parameters),
      "setPressureNetworkCover" => PressureNetworkCommands.SetPressureNetworkCoverAsync(parameters),
      "validatePressureNetwork" => PressureNetworkCommands.ValidatePressureNetworkAsync(parameters),
      "exportPressureNetwork" => PressureNetworkCommands.ExportPressureNetworkAsync(parameters),
      "connectPressureNetworks" => PressureNetworkCommands.ConnectPressureNetworksAsync(parameters),
      "addPressurePipe" => PressureNetworkCommands.AddPressurePipeAsync(parameters),
      "getPressurePipeProperties" => PressureNetworkCommands.GetPressurePipePropertiesAsync(parameters),
      "resizePressurePipe" => PressureNetworkCommands.ResizePressurePipeAsync(parameters),
      "addPressureFitting" => PressureNetworkCommands.AddPressureFittingAsync(parameters),
      "getPressureFittingProperties" => PressureNetworkCommands.GetPressureFittingPropertiesAsync(parameters),
      "addPressureAppurtenance" => PressureNetworkCommands.AddPressureAppurtenanceAsync(parameters),
      // Grading
      "listGradingGroups" => GradingCommands.ListGradingGroupsAsync(),
      "getGradingGroup" => GradingCommands.GetGradingGroupAsync(parameters),
      "createGradingGroup" => GradingCommands.CreateGradingGroupAsync(parameters),
      "deleteGradingGroup" => GradingCommands.DeleteGradingGroupAsync(parameters),
      "getGradingGroupVolume" => GradingCommands.GetGradingGroupVolumeAsync(parameters),
      "createSurfaceFromGradingGroup" => GradingCommands.CreateSurfaceFromGradingGroupAsync(parameters),
      "listGradings" => GradingCommands.ListGradingsAsync(parameters),
      "getGrading" => GradingCommands.GetGradingAsync(parameters),
      "createGrading" => GradingCommands.CreateGradingAsync(parameters),
      "deleteGrading" => GradingCommands.DeleteGradingAsync(parameters),
      "listGradingCriteria" => GradingCommands.ListGradingCriteriaAsync(),
      "listFeatureLines" => GradingCommands.ListFeatureLinesAsync(),
      "getFeatureLine" => GradingCommands.GetFeatureLineAsync(parameters),
      "exportFeatureLineAsPolyline" => GradingCommands.ExportFeatureLineAsPolylineAsync(parameters),
      "createFeatureLine" => GradingCommands.CreateFeatureLineAsync(parameters),
      // Project / data shortcuts
      "listDataShortcuts" => DataShortcutCommands.ListDataShortcutsAsync(),
      "createDataShortcut" => DataShortcutCommands.CreateDataShortcutAsync(parameters),
      "promoteDataShortcut" => DataShortcutCommands.PromoteDataShortcutAsync(parameters),
      "referenceDataShortcut" => DataShortcutCommands.ReferenceDataShortcutAsync(parameters),
      "syncDataShortcuts" => DataShortcutCommands.SyncDataShortcutsAsync(parameters),
      "createDataShortcutReference" => DataShortcutCommands.CreateDataShortcutReferenceAsync(parameters),
      // Point groups
      "createPointGroup" => PointGroupCommands.CreatePointGroupAsync(parameters),
      "updatePointGroup" => PointGroupCommands.UpdatePointGroupAsync(parameters),
      "deletePointGroup" => PointGroupCommands.DeletePointGroupAsync(parameters),
      "deletePipeNetwork" => PipeNetworkCommands.DeletePipeNetworkAsync(parameters),
      "deleteParcel" => ParcelEditingCommands.DeleteParcelAsync(parameters),
      "exportCogoPoints" => PointGroupCommands.ExportCogoPointsAsync(parameters),
      "transformCogoPoints" => PointGroupCommands.TransformCogoPointsAsync(parameters),
      // COGO
      "cogoInverse" => CogoCommands.CogoInverseAsync(parameters),
      "cogoDirectionDistance" => CogoCommands.CogoDirectionDistanceAsync(parameters),
      "cogoTraverse" => CogoCommands.CogoTraverseAsync(parameters),
      "cogoCurveSolve" => CogoCommands.CogoCurveSolveAsync(parameters),
      "listSurveyDatabases" => CogoCommands.ListSurveyDatabasesAsync(),
      "createSurveyDatabase" => CogoCommands.CreateSurveyDatabaseAsync(parameters),
      "listSurveyFigures" => CogoCommands.ListSurveyFiguresAsync(parameters),
      "getSurveyFigure" => CogoCommands.GetSurveyFigureAsync(parameters),
      "listSurveyObservations" => CogoCommands.ListSurveyObservationsAsync(parameters),
      "adjustSurveyNetwork" => CogoCommands.AdjustSurveyNetworkAsync(parameters),
      "createSurveyFigure" => CogoCommands.CreateSurveyFigureAsync(parameters),
      "importSurveyLandXml" => CogoCommands.ImportSurveyLandXmlAsync(parameters),
      // Alignment editing
      "alignmentAddTangent" => AlignmentEditCommands.AddTangentAsync(parameters),
      "alignmentAddCurve" => AlignmentEditCommands.AddCurveAsync(parameters),
      "alignmentAddSpiral" => AlignmentEditCommands.AddSpiralAsync(parameters),
      "alignmentDeleteEntity" => AlignmentEditCommands.DeleteEntityAsync(parameters),
      "alignmentSetStationEquation" => AlignmentEditCommands.SetStationEquationAsync(parameters),
      "alignmentSetReferencePoint" => AlignmentEditCommands.SetReferencePointAsync(parameters),
      "alignmentGetStationOffset" => AlignmentEditCommands.GetStationOffsetAsync(parameters),
      "alignmentOffsetCreate" => AlignmentEditCommands.OffsetCreateAsync(parameters),
      "alignmentWidenTransition" => AlignmentEditCommands.WidenTransitionAsync(parameters),
      // Profile editing
      "profileAddPvi" => ProfileEditCommands.AddPviAsync(parameters),
      "profileDeletePvi" => ProfileEditCommands.DeletePviAsync(parameters),
      "profileAddCurve" => ProfileEditCommands.AddCurveAsync(parameters),
      "profileSetGrade" => ProfileEditCommands.SetGradeAsync(parameters),
      "profileGetElevation" => ProfileEditCommands.GetElevationAsync(parameters),
      "profileCheckKValues" => ProfileEditCommands.CheckKValuesAsync(parameters),
      "profileViewCreate" => ProfileEditCommands.ProfileViewCreateAsync(parameters),
      "profileViewBandSet" => ProfileEditCommands.ProfileViewBandSetAsync(parameters),
      // Plan production
      "listSheetSets" => PlanProductionCommands.ListSheetSetsAsync(),
      "getSheetSetInfo" => PlanProductionCommands.GetSheetSetInfoAsync(parameters),
      "createSheetSet" => PlanProductionCommands.CreateSheetSetAsync(parameters),
      "addSheet" => PlanProductionCommands.AddSheetAsync(parameters),
      "getSheetProperties" => PlanProductionCommands.GetSheetPropertiesAsync(parameters),
      "setSheetTitleBlock" => PlanProductionCommands.SetSheetTitleBlockAsync(parameters),
      "createPlanProfileSheet" => PlanProductionCommands.CreatePlanProfileSheetAsync(parameters),
      "updatePlanProfileSheetAlignment" => PlanProductionCommands.UpdatePlanProfileSheetAlignmentAsync(parameters),
      "createSheetView" => PlanProductionCommands.CreateSheetViewAsync(parameters),
      "setSheetViewScale" => PlanProductionCommands.SetSheetViewScaleAsync(parameters),
      "publishSheetPdf" => PlanProductionCommands.PublishSheetPdfAsync(parameters),
      "exportSheetSet" => PlanProductionCommands.ExportSheetSetAsync(parameters),
      // QC checks
      "qcCheckAlignment" => QcCommands.QcCheckAlignmentAsync(parameters),
      "qcCheckProfile" => QcCommands.QcCheckProfileAsync(parameters),
      "qcCheckCorridor" => QcCommands.QcCheckCorridorAsync(parameters),
      "qcCheckPipeNetwork" => QcCommands.QcCheckPipeNetworkAsync(parameters),
      "qcCheckSurface" => QcCommands.QcCheckSurfaceAsync(parameters),
      "qcCheckLabels" => QcCommands.QcCheckLabelsAsync(parameters),
      "qcReportGenerate" => QcCommands.QcReportGenerateAsync(parameters),
      "qcCheckDrawingStandards" => QcCommands.QcCheckDrawingStandardsAsync(parameters),
      "qcFixDrawingStandards" => QcCommands.QcFixDrawingStandardsAsync(parameters),
      // Quantity takeoff
      "qtyCorridorVolumes" => QuantityCommands.QtyCorridorVolumesAsync(parameters),
      "qtySurfaceVolume" => QuantityCommands.QtySurfaceVolumeAsync(parameters),
      "qtyPipeNetworkLengths" => QuantityCommands.QtyPipeNetworkLengthsAsync(parameters),
      "qtyPressureNetworkLengths" => QuantityCommands.QtyPressureNetworkLengthsAsync(parameters),
      "qtyParcelAreas" => QuantityCommands.QtyParcelAreasAsync(parameters),
      "qtyAlignmentLengths" => QuantityCommands.QtyAlignmentLengthsAsync(parameters),
      "qtyPointCountByGroup" => QuantityCommands.QtyPointCountByGroupAsync(parameters),
      "qtyExportToCsv" => QuantityCommands.QtyExportToCsvAsync(parameters),
      "qtyMaterialListGet" => QuantityCommands.QtyMaterialListGetAsync(parameters),
      "qtyEarthworkSummary" => QuantityCommands.QtyEarthworkSummaryAsync(parameters),
      // Pipe hydraulics
    "calculatePipeNetworkHgl" => PipeHydraulicsCommands.CalculatePipeNetworkHglAsync(parameters),
    "analyzePipeNetworkHydraulics" => PipeHydraulicsCommands.AnalyzePipeNetworkHydraulicsAsync(parameters),
    "getPipeStructureProperties" => PipeHydraulicsCommands.GetPipeStructurePropertiesAsync(parameters),
      // Superelevation tools
    "getSuperelevation" => SuperelevationCommands.GetSuperelevationAsync(parameters),
    "setSuperelevation" => SuperelevationCommands.SetSuperelevationAsync(parameters),
    "checkSuperelevationDesign" => SuperelevationCommands.CheckSuperelevationDesignAsync(parameters),
    "generateSuperelevationReport" => SuperelevationCommands.GenerateSuperelevationReportAsync(parameters),
      // Assembly creation
    "createAssembly" => AssemblyCreationCommands.CreateAssemblyAsync(parameters),
      "createSubassembly" => AssemblyCreationCommands.CreateSubassemblyAsync(parameters),
      "editAssembly" => AssemblyCreationCommands.EditAssemblyAsync(parameters),
      "removeSubassembly" => AssemblyCreationCommands.RemoveSubassemblyAsync(parameters),
      // Sight distance
      "calculateSightDistance" => SightDistanceCommands.CalculateSightDistanceAsync(parameters),
      "checkStoppingDistance" => SightDistanceCommands.CheckStoppingDistanceAsync(parameters),
      // Detention basin
      "calculateDetentionBasinSize" => DetentionCommands.CalculateDetentionBasinSizeAsync(parameters),
      "calculateDetentionStageStorage" => DetentionCommands.CalculateDetentionStageStorageAsync(parameters),
      // Slope analysis
      "calculateSlopeGeometry" => SlopeAnalysisCommands.CalculateSlopeGeometryAsync(parameters),
      "checkSlopeStability" => SlopeAnalysisCommands.CheckSlopeStabilityAsync(parameters),
      // Cost estimation
      "exportPayItems" => CostEstimationCommands.ExportPayItemsAsync(parameters),
      "calculateMaterialCostEstimate" => CostEstimationCommands.CalculateMaterialCostEstimateAsync(parameters),
      // Labels
      "listLabelStyles" => LabelCommands.ListLabelStylesAsync(parameters),
      "listLabels" => LabelCommands.ListLabelsAsync(parameters),
      "addLabel" => LabelCommands.AddLabelAsync(parameters),
      "listStyles" => StyleCommands.ListStylesAsync(parameters),
      "getStyle" => StyleCommands.GetStyleAsync(parameters),
      // Style/label-set editing (2026-08-16)
      "setAlignmentStyle" => StyleEditCommands.SetAlignmentStyleAsync(parameters),
      "setProfileStyle" => StyleEditCommands.SetProfileStyleAsync(parameters),
      "setProfileViewStyle" => StyleEditCommands.SetProfileViewStyleAsync(parameters),
      // Catchment management
      "listCatchmentGroups" => CatchmentCommands.ListCatchmentGroupsAsync(),
      "getCatchmentGroup" => CatchmentCommands.GetCatchmentGroupAsync(parameters),
      "listCatchments" => CatchmentCommands.ListCatchmentsAsync(),
      "getCatchmentProperties" => CatchmentCommands.GetCatchmentPropertiesAsync(parameters),
      "setCatchmentProperties" => CatchmentCommands.SetCatchmentPropertiesAsync(parameters),
      "copyCatchmentToGroup" => CatchmentCommands.CopyCatchmentToGroupAsync(parameters),
      "getCatchmentFlowPath" => CatchmentCommands.GetCatchmentFlowPathAsync(parameters),
      "getCatchmentBoundary" => CatchmentCommands.GetCatchmentBoundaryAsync(parameters),
      // Time of concentration & hydrograph
      "calculateTimeOfConcentration" => TimeOfConcentrationCommands.CalculateTimeOfConcentrationAsync(parameters),
      "generateHydrograph" => TimeOfConcentrationCommands.GenerateHydrographAsync(parameters),
      "listTcMethods" => TimeOfConcentrationCommands.ListTcMethodsAsync(),
      // Storm and Sanitary Analysis (STM)
      "exportStm" => StmCommands.ExportStmAsync(parameters),
      "importStm" => StmCommands.ImportStmAsync(parameters),
      "openStormSanitaryAnalysis" => StmCommands.OpenStormSanitaryAnalysisAsync(parameters),
      "listSsaCapabilities" => StmCommands.ListSsaCapabilitiesAsync(),
      "getSelection" => AcadCommands.GetSelectionAsync(),
      "getEntityInfo" => AcadCommands.GetEntityInfoAsync(parameters),
      "getBlockInfo" => AcadCommands.GetBlockInfoAsync(parameters),
      "setEntityColor" => AcadCommands.SetEntityColorAsync(parameters),
      "mirrorEntity" => AcadCommands.MirrorEntityAsync(parameters),
      "executeCommand" => AcadCommands.ExecuteCommandAsync(parameters),
      "runLisp" => AcadCommands.RunLispAsync(parameters),
      "deleteEntity" => AcadCommands.DeleteEntityAsync(parameters),
      "moveEntity" => AcadCommands.MoveEntityAsync(parameters),
      "copyEntity" => AcadCommands.CopyEntityAsync(parameters),
      "rotateEntity" => AcadCommands.RotateEntityAsync(parameters),
      "scaleEntity" => AcadCommands.ScaleEntityAsync(parameters),
      "selectByCriteria" => AcadCommands.SelectByCriteriaAsync(parameters),
      "getLayers" => AcadCommands.GetLayersAsync(),
      "createLayer" => AcadCommands.CreateLayerAsync(parameters),
      // 2026-08-07 P0-1: 批量/枚举方法（此前缺失导致 METHOD_NOT_FOUND）
      "setVisualStyle" => AcadCommands.SetVisualStyleAsync(parameters),
      "getEntitiesByLayer" => AcadCommands.GetEntitiesByLayerAsync(parameters),
      "getBlocksByLayer" => AcadCommands.GetBlocksByLayerAsync(parameters),   // 2026-08-19: 批量读块属性(高程常存于属性/块内文字)
      "getEntitiesByBlock" => AcadCommands.GetEntitiesByBlockAsync(parameters),
      "getSelectionDetail" => AcadCommands.GetSelectionDetailAsync(parameters),
      "selectEntities" => AcadCommands.SelectEntitiesAsync(parameters),              // 2026-08-08: 程序化选中
      "getDrawingOverview" => AcadCommands.GetDrawingOverviewAsync(parameters),      // 2026-08-08: 图纸概况
      "analyzeLayer" => AcadCommands.AnalyzeLayerAsync(parameters),                     // 2026-08-13: 图层画像
      "listDirectory" => AcadCommands.ListDirectoryAsync(parameters),                    // 2026-08-13: 只读列目录
      "readTextFile" => AcadCommands.ReadTextFileAsync(parameters),                      // 2026-08-13: 只读文本前 N 行
      "readDocx" => FileFormatCommands.ReadDocxAsync(parameters),                          // 2026-08-13: Word 文档
      "readXlsx" => FileFormatCommands.ReadXlsxAsync(parameters),                          // 2026-08-13: Excel 表格
      "readPptx" => FileFormatCommands.ReadPptxAsync(parameters),                          // 2026-08-13: PPT 文档
      "readZip" => FileFormatCommands.ReadZipAsync(parameters),                            // 2026-08-13: 压缩包
      "readDoc" => FileFormatCommands.ReadDocAsync(parameters),                          // 2026-09-11: Word .doc 老格式(OLE2 二进制)
      "readXls" => FileFormatCommands.ReadXlsAsync(parameters),                          // 2026-09-11: Excel .xls 老格式(BIFF8 二进制)
      "writeTextFile" => AcadCommands.WriteTextFileAsync(parameters),                     // 2026-08-13: 用户明示路径写文件
      "exportSelectionToFile" => AcadCommands.ExportSelectionToFileAsync(parameters),  // 2026-08-07: 数据出口通道
      "setEntitiesColor" => AcadCommands.SetEntitiesColorAsync(parameters),
      "setEntityLayer" => AcadCommands.SetEntityLayerAsync(parameters),
      "setEntityLinetype" => AcadCommands.SetEntityLinetypeAsync(parameters),
      "setEntityLineweight" => AcadCommands.SetEntityLineweightAsync(parameters),
      "setEntityTransparency" => AcadCommands.SetEntityTransparencyAsync(parameters),
      "setLayerColor" => AcadCommands.SetLayerColorAsync(parameters),
      "setLayerLinetype" => AcadCommands.SetLayerLinetypeAsync(parameters),
      "setLayerLineweight" => AcadCommands.SetLayerLineweightAsync(parameters),
      "setLayerTransparency" => AcadCommands.SetLayerTransparencyAsync(parameters),
      "moveEntities" => AcadCommands.MoveEntitiesAsync(parameters),
      "deleteEntities" => AcadCommands.DeleteEntitiesAsync(parameters),
      "copyEntities" => AcadCommands.CopyEntitiesAsync(parameters),   // 2026-08-08: 批量
      "mirrorEntities" => AcadCommands.MirrorEntitiesAsync(parameters), // 2026-08-08: 批量
      "rotateEntities" => AcadCommands.RotateEntitiesAsync(parameters), // 2026-08-08: 批量
      "scaleEntities" => AcadCommands.ScaleEntitiesAsync(parameters),   // 2026-08-08: 批量
      // Phase 1: 编辑操作
      "offsetEntity" => AcadCommands.OffsetEntityAsync(parameters),
      "breakEntity" => AcadCommands.BreakEntityAsync(parameters),
      "joinEntities" => AcadCommands.JoinEntitiesAsync(parameters),
      "explodeEntity" => AcadCommands.ExplodeEntityAsync(parameters),
      "probeGeometry" => AcadCommands.ProbeGeometryAsync(parameters),
      "filletEntities" => AcadCommands.FilletEntitiesAsync(parameters),
      "chamferEntities" => AcadCommands.ChamferEntitiesAsync(parameters),
      "trimEntity" => AcadCommands.TrimEntityAsync(parameters),
      "extendEntity" => AcadCommands.ExtendEntityAsync(parameters),
      "stretchEntity" => AcadCommands.StretchEntityAsync(parameters),
      "arrayEntity" => AcadCommands.ArrayEntityAsync(parameters),
      "alignEntity" => AcadCommands.AlignEntityAsync(parameters),
      "overkillEntities" => AcadCommands.OverkillEntitiesAsync(parameters),
      "layerOff" => AcadCommands.LayerOffAsync(parameters),
      "layerFreeze" => AcadCommands.LayerFreezeAsync(parameters),
      "layerLock" => AcadCommands.LayerLockAsync(parameters),
      "layerUnlock" => AcadCommands.LayerUnlockAsync(parameters),
      "layerIsolate" => AcadCommands.LayerIsolateAsync(parameters),
      "layerMatch" => AcadCommands.LayerMatchAsync(parameters),
      "createBlock" => AcadCommands.CreateBlockAsync(parameters),
      "insertBlock" => AcadCommands.InsertBlockAsync(parameters),
      "explodeBlock" => AcadCommands.ExplodeBlockAsync(parameters),
      "writeBlock" => AcadCommands.WriteBlockAsync(parameters),
      "dimLinear" => AcadCommands.DimLinearAsync(parameters),
      "dimAligned" => AcadCommands.DimAlignedAsync(parameters),
      "dimRadius" => AcadCommands.DimRadiusAsync(parameters),
      "dimDiameter" => AcadCommands.DimDiameterAsync(parameters),
      "dimAngular" => AcadCommands.DimAngularAsync(parameters),
      "getDimensionInfo" => AcadCommands.GetDimensionInfoAsync(parameters),
      "editText" => AcadCommands.EditTextAsync(parameters),
      "editCogoPoint" => PointCommands.EditCogoPointAsync(parameters),
      "editGrading" => GradingCommands.EditGradingAsync(parameters),
      "editLabel" => LabelCommands.EditLabelAsync(parameters),
      "scaleText" => AcadCommands.ScaleTextAsync(parameters),
      "attachXref" => AcadCommands.AttachXrefAsync(parameters),
      "measureDist" => AcadCommands.MeasureDistAsync(parameters),
      "measureArea" => AcadCommands.MeasureAreaAsync(parameters),
      "extrudeSolid" => AcadCommands.ExtrudeSolidAsync(parameters),
      "revolveSolid" => AcadCommands.RevolveSolidAsync(parameters),
      "loftSolid" => AcadCommands.LoftSolidAsync(parameters),
      "createNurbsSurface" => AcadCommands.CreateNurbsSurfaceAsync(parameters),
      "editNurbsControlPoints" => AcadCommands.EditNurbsControlPointsAsync(parameters),
      "thickenSurface" => AcadCommands.ThickenSurfaceAsync(parameters),
      "sweepSolid" => AcadCommands.SweepSolidAsync(parameters),
      "booleanUnion" => AcadCommands.BooleanUnionAsync(parameters),
      "booleanSubtract" => AcadCommands.BooleanSubtractAsync(parameters),
      "move3d" => AcadCommands.Move3dAsync(parameters),
      "mirror3d" => AcadCommands.Mirror3dAsync(parameters),
      "rotate3d" => AcadCommands.Rotate3dAsync(parameters),
      "array3d" => AcadCommands.Array3dAsync(parameters),
      "sliceSolid" => AcadCommands.SliceSolidAsync(parameters),
      "sectionPlane" => AcadCommands.SectionPlaneAsync(parameters),
      "interferenceCheck" => AcadCommands.InterferenceCheckAsync(parameters),
      "convertToSurface" => AcadCommands.ConvertToSurfaceAsync(parameters),
      "convertToSolid" => AcadCommands.ConvertToSolidAsync(parameters),
      "renderScene" => AcadCommands.RenderSceneAsync(parameters),
      "renameLayer" => AcadCommands.RenameLayerAsync(parameters),
      "deleteLayer" => AcadCommands.DeleteLayerAsync(parameters),
      "renameSurface" => SurfaceCommands.RenameSurfaceAsync(parameters),
      "assignMaterial" => AcadCommands.AssignMaterialAsync(parameters),
      "listMethods" => ListMethodsAsync(),
      _ => throw new JsonRpcDispatchException("CIVIL3D.METHOD_NOT_FOUND", $"Plugin method '{method}' is not implemented yet."),
    };
  }

  // 反射方法名 → 实际注册名（CommandDispatcher switch 注册名带域前缀/别名，
  // 裸反射名直接调会 METHOD_NOT_FOUND，2026-08-06 桩号排查中发现）。
  private static readonly Dictionary<string, string[]> RegisteredNameOverrides = new()
  {
    ["stationToPoint"] = new[] { "alignmentStationToPoint" },
    ["sampleStations"] = new[] { "alignmentSampleStations" },
    ["pointToStation"] = new[] { "alignmentPointToStation" },
    ["addTangent"] = new[] { "alignmentAddTangent" },
    ["addCurve"] = new[] { "alignmentAddCurve", "profileAddCurve" },
    ["addSpiral"] = new[] { "alignmentAddSpiral" },
    ["setReferencePoint"] = new[] { "alignmentSetReferencePoint" },
    ["setStationEquation"] = new[] { "alignmentSetStationEquation" },
    ["getStationOffset"] = new[] { "alignmentGetStationOffset" },
    ["offsetCreate"] = new[] { "alignmentOffsetCreate" },
    ["widenTransition"] = new[] { "alignmentWidenTransition" },
    ["traceFlowPath"] = new[] { "traceHydrologyFlowPath" },
    ["findLowPoint"] = new[] { "findHydrologyLowPoint" },
    ["estimateRunoff"] = new[] { "estimateHydrologyRunoff" },
    ["addPvi"] = new[] { "profileAddPvi" },
    ["deletePvi"] = new[] { "profileDeletePvi" },
    ["setGrade"] = new[] { "profileSetGrade" },
    ["getElevation"] = new[] { "profileGetElevation" },
    ["checkKValues"] = new[] { "profileCheckKValues" },
  };

  // 反射扫不到但实际注册的方法（workflow 别名/Job/内部方法），补发进清单。
  private static readonly string[] AdditionalRegisteredNames =
  {
    "corridorQcReportWorkflow", "surfaceComparisonReportWorkflow",
    "dataShortcutPublishSyncWorkflow", "dataShortcutReferenceSyncWorkflow",
    "projectStartupWorkflow", "projectReferenceSetupWorkflow",
    "drawingReadinessAuditWorkflow", "featureLineToGradingWorkflow",
    "planProductionPublishWorkflow", "qcFixAndVerifyWorkflow",
    "newDrawing", "getJobStatus", "cancelJob",
    "addSurfaceWatershed", "watershedRunoffWorkflow",
    "runoffDetentionWorkflow", "runoffPipeWorkflow",
    "syncDataShortcuts", "alignmentDeleteEntity", "listMethods",
    "profileViewCreate", "profileViewBandSet",
  };

  /// <summary>
  /// 列出所有可用方法（反射扫描静态命令类 + 注册名修正，AI 先查清单再调用，避免猜方法名）。
  /// </summary>
  private static Task<object?> ListMethodsAsync()
  {
    var names = new HashSet<string>();
    try
    {
      var asm = typeof(CommandDispatcher).Assembly;
      foreach (var t in asm.GetTypes())
      {
        if (!t.IsClass || !t.IsAbstract || !t.IsSealed) continue; // 静态类
        foreach (var m in t.GetMethods(System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.Static))
        {
          if (!m.Name.EndsWith("Async") || m.ReturnType != typeof(Task<object?>)) continue;
          var n = m.Name[..^"Async".Length];
          if (n.Length > 0 && char.IsUpper(n[0])) n = char.ToLowerInvariant(n[0]) + n[1..];
          if (RegisteredNameOverrides.TryGetValue(n, out var registered))
          {
            foreach (var r in registered) names.Add(r);
          }
          else
          {
            names.Add(n);
          }
        }
      }
    }
    catch { }
    foreach (var extra in AdditionalRegisteredNames) names.Add(extra);
    names.Remove("dispatch"); // 内部入口，不对外
    var sorted = names.OrderBy(x => x, StringComparer.OrdinalIgnoreCase).ToList();
    // 2026-08-10: 353 个方法全覆盖描述（按域批量补全；中性说明，不写频率/偏好词）
    var descriptions = new Dictionary<string, string>
    {
      ["addCorridorRegion"] = "廊道加区域 {corridorName, assemblyName, startStation, endStation, baselineIndex?, frequency?, frequencyAtCurves?, frequencyAtKneePoints?, regionName?}",
      ["createCorridor"] = "创建廊道 {corridorName, alignmentName, assemblyName, baselineName?, regionName?, startStation?, endStation?, profileName?, surfaceName?, style?}——路线+装配→廊道，可选纵断面/曲面/样式",
      ["addCorridorSurface"] = "一键给廊道加曲面 {name, surfaceName?, codes?:[...], asBreakLine?}——从部件链接码生成廊道曲面（不传 codes 则自动收集链接码）；模型算量用",
      ["addLabel"] = "创建标签 {objectType, objectName, labelType, labelStyle?, increment?, station?}（路线桩号/曲面高程/纵断等）",
      ["addPipeToNetwork"] = "添加管道 {networkName, partName, diameter?, startStructure?, endStructure?}",
      ["addPressureAppurtenance"] = "添加压力管网附属设备 {networkName, partName, rotation?, onPipeName?}",
      ["addPressureFitting"] = "添加压力管件 {networkName, partName, rotation?}",
      ["addPressurePipe"] = "添加压力管道 {networkName, partName, diameter?}",
      ["addSheet"] = "添加图纸 {sheetSetName, sheetName, sheetNumber?, layoutName?}——向图纸集添加新图纸",
      ["addStructureToNetwork"] = "添加检查井/结构物到管网 {networkName, x, y, partName, rimElevation?, sumpDepth?}",
      ["addSurfaceBoundary"] = "添加曲面边界 {name, boundaryType?}",
      ["addSurfaceBreakline"] = "添加断裂线 {name, description?, breaklineType?}",
      ["addSurfacePoints"] = "向曲面添加高程点 {name, points:[{x,y,z}], description?}——points 必填数组",
      ["addSurfacePointsFromFile"] = "文件通道批量加曲面点 {name, filePath, delimiter?, hasHeader?, xCol?, yCol?, zCol?, skipRows?}——大量点用",
      ["addSurfaceWatershed"] = "添加汇水区分析 {name, depthThreshold?, mergeAdjacentWatersheds?}",
      ["addSurfaceWatersheds"] = "添加多个汇水区分析 {name, depthThreshold?, mergeAdjacentWatersheds?}",
      ["adjustParcelLotLine"] = "调整地块界线（lot line） {siteName, parcelName, targetAreaSqFt, lotLineHandle?, tolerance?}",
      ["adjustSurveyNetwork"] = "测量网平差 {networkName, databaseName}——对测量网络执行平差计算",
      ["alignEntity"] = "对齐图元 {handle, srcX, srcY, dstX, dstY}",
      ["alignmentAddCurve"] = "路线添加缓和曲线段 {alignmentName, passThroughX, passThroughY, radius}",
      ["alignmentAddSpiral"] = "路线添加螺旋线 {alignmentName, startX, startY, startRadius, endRadius, length, spiralType?}",
      ["alignmentAddTangent"] = "路线添加直线段 {alignmentName, startX, startY, endX, endY}",
      ["alignmentDeleteEntity"] = "删除路线子图元 {handle}",
      ["alignmentGetStationOffset"] = "路线某点的桩号+偏移 {alignmentName, x, y}",
      ["alignmentOffsetCreate"] = "偏移路线 {alignmentName, offsetName, offset, layer?, style?, labelSet?}",
      ["alignmentPointToStation"] = "坐标转桩号 {name, x, y}——将坐标点换算为路线桩号+偏移",
      ["alignmentSampleStations"] = "路线采样桩号 {name, stations:[], offset?}",
      ["alignmentSetReferencePoint"] = "设置路线桩号参考点（锚点+station） {alignmentName, x, y, station?}",
      ["alignmentSetStationEquation"] = "设置桩号方程 {alignmentName, rawStation, nominalStation}",
      ["alignmentStationToPoint"] = "桩号转坐标 {name, station, offset?}",
      ["alignmentWidenTransition"] = "路线加宽过渡段 {alignmentName, side, startStation, endStation, startOffset, endOffset, offsetName?}",
      ["analyzePipeNetworkHydraulics"] = "管网水力分析 {networkName, designFlow?, manningsN?, minCoverDepth?, minVelocity?, maxVelocity?, minSlope?}",
      ["analyzeSurfaceDirections"] = "曲面坡向分析 {name, numRanges?}",
      ["analyzeSurfaceElevation"] = "曲面高程分析 {name, ranges:[], numRanges?}",
      ["analyzeSurfaceSlope"] = "曲面坡度分析 {name, ranges:[], numRanges?}",
      ["array"] = "阵列（同 arrayEntity）",
      ["array3d"] = "三维阵列 {handle, type: rect|polar, count, rows?, cols?, levels?, dx?, dy?, dz?}",
      ["arrayEntity"] = "阵列图元 {handle, type, count, dx?, dy?, rows?, cols?}",
      ["assignMaterial"] = "赋予材质 {handle, materialName}",
      ["assignPressurePartsList"] = "分配压力管网部件清单 {networkName, partsList}",
      ["attachXref"] = "附着外部参照 {filePath, x, y, scale?, rotation?}",
      ["booleanSubtract"] = "布尔差集 {mainHandle, toolHandle}（main 减 tool）",
      ["booleanUnion"] = "布尔并集 {handles:[]}",
      ["breakEntity"] = "打断图元 {handle, x, y}",
      ["calculateCatchmentArea"] = "计算汇水区面积 {surfaceName, outletX, outletY, sampleSpacing?, maxDistance?}",
      ["calculateDetentionBasinSize"] = "计算调蓄池尺寸 {inflow, outflow, stormDuration?, method?, sideSlope?, bottomWidth?, freeboardDepth?}",
      ["calculateDetentionStageStorage"] = "计算调蓄池水位-容积 {surfaceName, bottomElevation, topElevation, elevationIncrement?, outletType?, outletDiameter?, weirLength?, dischargeCoefficient?}",
      ["calculateMaterialCostEstimate"] = "材料造价估算 {corridorName?, baseSurface?, designSurface?, alignmentName?, contingencyPercent?, mobilizationPercent?, outputPath?, overwrite?}",
      ["calculatePipeNetworkHgl"] = "计算管网水压线（HGL） {networkName, tailwaterElevation?, designFlow?, manningsN?}",
      ["calculateSightDistance"] = "计算视距 {alignmentName?, designSpeed, speedUnits?, sightDistanceType?, grade?, perceptionReactionTime?, frictionCoefficient?, profileName?, checkStation?}——停车视距/超车视距计算",
      ["calculateSlopeGeometry"] = "边坡几何计算 {alignmentName?, profileName?, surfaceName?, cutSlopeRatio?, fillSlopeRatio?, benchWidth?, benchHeightInterval?, stationStart?, stationEnd?, stationInterval?, roadwayWidth?}",
      ["calculateSurfaceVolume"] = "计算曲面体积（两曲面间） {baseSurface, comparisonSurface, method?}",
      ["calculateSurfaceVolumeByRegion"] = "按区域计算曲面体积 {baseSurface, comparisonSurface}",
      ["calculateTimeOfConcentration"] = "计算汇流时间 {method}",
      ["cancelJob"] = "取消后台任务",
      ["chamferEntities"] = "倒角 {distance1, distance2, handle1, handle2}",
      ["checkPipeNetworkInterference"] = "管网碰撞检查 {networkName, targetType, targetName}",
      ["checkSlopeStability"] = "边坡稳定性检查 {}",
      ["checkStoppingDistance"] = "停车视距检查 {alignmentName, profileName, designSpeed, stationStart?, stationEnd?, stationInterval?}",
      ["checkSuperelevationDesign"] = "超高设计检查 {alignmentName, designSpeed, maxSuperelevation?, checkAttainmentLength?, checkRunoffLength?}",
      ["cogoCurveSolve"] = "曲线要素计算 {radius?, deltaDegrees?, length?, tangent?, chord?}",
      ["cogoDirectionDistance"] = "方向+距离计算坐标 {fromX, fromY, bearingDegrees, distance, fromZ?, slope?}",
      ["cogoInverse"] = "坐标反算（两点距离/方位角） {x1, y1, x2, y2}",
      ["cogoTraverse"] = "导线计算 {courses:[], startX, startY, startZ?, isClosed?}——从导线边数据解算坐标（角度/距离）",
      ["computeCorridorVolumes"] = "计算廊道体积 {name, corridorSurface, referenceSurface}",
      ["computeSurfaceVolume"] = "计算曲面体积（同 calculateSurfaceVolume） {baseSurface, comparisonSurface}",
      ["connectPressureNetworks"] = "连接压力管网 {targetNetwork, sourceNetwork}",
      ["convertToSolid"] = "转实体 {handle}——将曲面/网格转换为三维实体",
      ["convertToSurface"] = "转曲面 {handle}——将实体/网格转换为曲面",
      ["copyCatchmentToGroup"] = "复制汇水区到组 {catchmentName, targetGroupName}",
      ["copyEntities"] = "批量复制 {handles:[], dx?, dy?}",
      ["copyEntity"] = "复制单个图元 {handle, dx?, dy?}",
      ["corridorQcReportWorkflow"] = "廊道质检报告向导（多步）",
      ["create3dPolyline"] = "创建三维多段线 {points:[{x,y,z}], closed?, layer?}",
      ["createAlignment"] = "创建路线 {name, handle?, bulges:[], points:[], layer?, style?, labelSet?, site?}——handle 模式引用现有多段线（保留圆弧）",
      ["createAssembly"] = "创建装配 {name, insertX, insertY, assemblyType, description?}",
      ["createBlock"] = "创建块（从选中图元） {name, handles:[], x?, y?}",
      ["createBox"] = "创建 3D 长方体 {x?, y?, z?, length, width, height, layer?}",
      ["createCircle"] = "画圆 {center:[x,y], diameter}",
      ["createCogoPoints"] = "创建 Cogo 点 {points:[{x,y,z,pointNumber?}], startNumber?}",
      ["createCone"] = "创建 3D 圆锥 {x?, y?, z?, radius, height, layer?}——⚠️ z=中心高度非底高(底=z-h/2, 顶=z+h/2)",
      ["createCylinder"] = "创建 3D 圆柱 {x?, y?, z?, radius, height, layer?}",
      ["createDataShortcut"] = "创建数据快捷方式 {objectType, objectName, description?, projectFolder?}",
      ["createDataShortcutReference"] = "创建数据快捷方式引用 {sourceFilePath, objectName, objectType}",
      ["createFeatureLine"] = "创建特征线 {points:[], name?, layer?}",
      ["createGrading"] = "创建放坡 {groupName, featureLineName, criteriaName?, side?}",
      ["createGradingGroup"] = "创建放坡组 {name, description?, useProjection?}",
      ["createIntersection"] = "创建交叉口 {name, mainRoadAlignment, mainRoadProfile, intersectingRoadAlignment, intersectingRoadProfile}——在路线交点处创建交叉口对象",
      ["createLayer"] = "创建图层 {name, color?}",
      ["createLayoutProfile"] = "创建设计纵断面（布局） {alignmentName, profileName, layer?, style?, labelSet?}",
      ["createLineSegment"] = "画直线 {startX, startY, endX, endY, startZ?, endZ?, layer?}",
      ["createMText"] = "创建多行文字 {text, x, y, z?, width?, textHeight?, rotation?, layer?}",
      ["createParcel"] = "创建地块 {siteName, points:[], name?, sourceHandle?, style?, areaLabelStyle?}",
      ["createPipeNetwork"] = "创建管网 {name, partsList, layer?, style?, referenceSurface?, referenceAlignment?}",
      ["createPlanProfileSheet"] = "创建平面/纵断图纸 {sheetSetName, alignmentName}",
      ["createPointGroup"] = "创建点组 {name, description?, includeNumbers?, excludeNumbers?, includeDescriptions?}",
      ["createPolyline"] = "画多段线 {points:[{x,y}], closed?, layer?, bulges:[]}",
      ["createPressureNetwork"] = "创建压力管网 {name, partsList, layer?, referenceSurface?, referenceAlignment?}",
      ["createProfileFromSurface"] = "由曲面生成纵断面 {alignmentName, surfaceName, profileName, layer?, style?, labelSet?}",
      ["createSampleLines"] = "创建采样线 {alignmentName, groupName, leftWidth, rightWidth, stations:[], surfaces:[], interval?}",
      ["createSectionViewGroup"] = "创建横断面图组 {alignmentName, sampleLineGroupName, insertionX, insertionY, style?, plotStyle?, rows?, columns?, gapX?, gapY?}",
      ["createSectionViews"] = "创建横断面图 {sampleLineGroupName, alignmentName, insertionX, insertionY, style?, bandSetStyle?, leftOffset?, rightOffset?, stationStart?, stationEnd?, rows?, gapBetweenViews?}",
      ["createSheetSet"] = "创建图纸集 {name}——新建图纸集（DST 管理）",
      ["createSheetView"] = "创建图纸视图 {layoutName, viewName?, centerX?, centerY?, width?, height?, scale?}",
      ["createSphere"] = "创建 3D 球 {x?, y?, z?, radius, layer?}",
      ["createSubassembly"] = "创建子装配 {assemblyName, subassemblyType, side}——新建子装配（用于装配组合）",
      ["createSurface"] = "创建曲面 {name, style?, layer?, description?}",
      ["createSurfaceFromDem"] = "从 DEM 创建曲面 {filePath, name, style?, layer?, description?, coordinateSystem?}",
      ["createSurfaceFromGradingGroup"] = "从放坡组创建曲面 {name, surfaceName?}",
      ["createSurveyDatabase"] = "创建测量数据库 {name}",
      ["createSurveyFigure"] = "创建测量图形 {databaseName, figureName, pointNumbers:[]}",
      ["createText"] = "创建单行文字 {text, x, y, z?, height?, rotation?, layer?}",
      ["createTorus"] = "创建 3D 圆环 {x?, y?, z?, majorRadius, minorRadius, layer?}",
      ["createWedge"] = "创建 3D 楔体 {x?, y?, z?, length, width, height, layer?}",
      ["dataShortcutPublishSyncWorkflow"] = "数据快捷方式发布同步向导（多步）",
      ["dataShortcutReferenceSyncWorkflow"] = "数据快捷方式引用同步向导（多步）",
      ["deleteAlignment"] = "删除路线 {name}",
      ["deleteCogoPoints"] = "删除 Cogo 点 {pointNumbers:[]}",
      ["deleteCorridorRegion"] = "廊道删区域 {corridorName, regionIndex, baselineIndex?}",
      ["deleteEntities"] = "批量删除 {handles:[]}",
      ["deleteEntity"] = "删除单个图元 {handle}",
      ["deleteGrading"] = "删除放坡 {groupName, handle}——从放坡组删除指定放坡",
      ["deleteGradingGroup"] = "删除放坡组 {name}——删除整个放坡组",
      ["deletePointGroup"] = "删除点组 {name}——删除指定点组",
      ["deleteParcel"] = "删除地块 {site, parcel}",
      ["deletePipeNetwork"] = "删除重力管网 {name}",

      ["deletePressureNetwork"] = "删除压力管网 {name}",
      ["deleteProfile"] = "删除纵断面 {alignmentName, profileName}——删除路线下的纵断面",
      ["deleteSurface"] = "删除曲面 {name}",
      ["delineateWatershed"] = "划分流域边界 {surfaceName, outletX, outletY, gridSpacing?, searchRadius?}",
      ["dimAligned"] = "对齐标注 {x1, y1, x2, y2, dimX, dimY, layer?}",
      ["dimAngular"] = "角度标注 {handle1, handle2, dimX, dimY}",
      ["dimDiameter"] = "直径标注 {handle, dimX?, dimY?, layer?}",
      ["dimLinear"] = "线性标注 {x1, y1, x2, y2, dimX, dimY, layer?}",
      ["dimRadius"] = "半径标注 {handle, dimX?, dimY?, layer?}——dimX/dimY 可选=标注方向(不参与测量), 测量值恒=圆真实半径",
      ["getDimensionInfo"] = "读取标注实体信息 {handle}——返回 measurement 测量值/type/dimensionText/textPosition/几何点, 用于标注自检",
      ["drawingReadinessAuditWorkflow"] = "图纸就绪审计向导（多步检查）",
      ["editAssembly"] = "编辑装配 {assemblyName, subassemblyName?, delete?}——修改装配结构/子装配",
      ["removeSubassembly"] = "删除子装配 {assemblyName, subassemblyName?, handle?}——从装配中移除指定子装配（按名称或 handle 定位）",
      ["editParcel"] = "编辑地块 {siteName, parcelName, newName?, style?, areaLabelStyle?, description?}——修改地块属性/边界",
      ["editText"] = "编辑文字内容 {handle, newText}",
      ["editCogoPoint"] = "编辑 Cogo 点 {pointNumber, newNumber?, description?, elevation?}",
      ["editGrading"] = "编辑放坡 {groupName, handle, newName?, description?, layer?}",
      ["editLabel"] = "编辑标签 {handle, styleName?, textOverride?, x?, y?}",
      ["estimateHydrologyRunoff"] = "估算水文径流 {drainageArea, runoffCoefficient, rainfallIntensity, areaUnits, intensityUnits}",
      ["executeCommand"] = "执行非交互 CAD 命令（交互命令会被白名单拦截） {command}",
      ["explodeBlock"] = "炸开块引用 {handle}",
      ["explodeEntity"] = "炸开图元 {handle}",
      ["probeGeometry"] = "非破坏几何探测 {handle, maxDepth?=12}——内存 Explode 递归展开块引用，返回可见几何图元（Circle=点标记/Line|Arc|Polyline=连接/Hatch=造型），不落库不删除；读 SAC 子装配/装配真实几何用（Points/Links 集合对 .NET 生成器运行时为空）",
      ["exportCogoPoints"] = "导出 Cogo 点 {format: csv/pnezd/penz/xyzd/xyz, groupName?, pointNumbers:[], delimiter?}——返回数据字符串",
      ["exportFeatureLineAsPolyline"] = "特征线导出为多段线 {name, targetLayer?}",
      ["exportPayItems"] = "导出支付项（pay items） {outputPath, corridorName?, baseSurface?, designSurface?, alignmentName?, includeEarthwork?, includeCorridorMaterials?, includePipeLengths?, includeStructureCounts?, overwrite?}",
      ["exportPressureNetwork"] = "导出压力管网 {networkName}",
      ["exportSectionData"] = "导出横断面数据（CSV）{sampleLineGroupName, outputPath, alignmentName, includeElevations?, includeMaterials?, stationStart?, stationEnd?, overwrite?}",
      ["exportSelectionToFile"] = "导出选中集到文件 {path, format:\"csv\"|\"json\", delimiter?, header?}：用户要坐标文件→csv(x,y,z 每行)，AI 自用/跨图→json——⚠️ 文件已存在则拒绝覆盖(换新路径)",
      ["exportSheetSet"] = "导出图纸集 {sheetSetName, outputPath, overwrite?}——导出图纸集数据/清单",
      ["exportStm"] = "导出 STM（雨污模型）文件 {filePath?}",
      ["extendEntity"] = "延伸图元 {boundaryHandle, targetHandle}",
      ["extractSurfaceContours"] = "提取等高线 {name, minorInterval, majorInterval}",
      ["extrudeSolid"] = "拉伸成实体 {handle, height, taperAngle?}",
      ["featureLineToGradingWorkflow"] = "特征线转放坡向导（多步）",
      ["filletEntities"] = "圆角 {radius, handle1, handle2}",
      ["findHydrologyLowPoint"] = "查找水文低点 {surfaceName, sampleSpacing?}",
      ["generateHydrograph"] = "生成流量过程线（水文曲线） {method?}",
      ["generateSuperelevationReport"] = "生成超高报告 {alignmentName, outputPath?, includeRunoffTable?, includeViolations?, overwrite?}",
      ["getAlignment"] = "读取路线信息 {name}",
      ["getAssembly"] = "读取装配 {name}——获取装配信息（子装配/结构）",
      ["getSubassemblyGeometry"] = "读取装配内子部件的几何与挂载链 {assemblyName}——每个子部件返回 side / hookTo(父部件名) / hookToHandle / pointIndexHookTo / status / isDynamic / points[{index, codes, Offset?, Elevation?}] / links[{index, codes, points[]}] / shapes[{index, codes}]；诊断 hook 与几何生成用（几何点需装配布局生成后才有）",
      ["verifyAssemblyGeometry"] = "装配几何校验 {assemblyName}——probe 每个子部件实体几何，返回 pointCount(几何点)/linkCount(连接线C-ROAD-LINK)/shapeLineCount(造型边界线C-ROAD-SHAP,与link重叠不计入)/shapeCount(结构层hatch)/width|height(点相对跨度)/hatchAreas(层面积)/points(相对坐标)；AI 建完装配后自查几何是否符合预期（层数/宽度/深度），非破坏",
      ["getBlockInfo"] = "读取块信息（块名/位置/旋转/缩放） {handle}",
      ["getCatchmentBoundary"] = "读取汇水区边界 {catchmentName}",
      ["getCatchmentFlowPath"] = "读取汇水区汇流路径 {catchmentName}",
      ["getCatchmentGroup"] = "读取汇水区组 {groupName}",
      ["getCatchmentProperties"] = "读取汇水区属性 {catchmentName}",
      ["getCivil3DHealth"] = "检查插件/图纸状态（在线、卡顿、文档信息）",
      ["getCogoPoint"] = "读取 Cogo 点 {pointNumber}",
      ["getCoordinateSystemInfo"] = "读取当前坐标系信息",
      ["getCorridor"] = "读取廊道信息 {name}",
      ["getCorridorFeatureLines"] = "读取廊道特征线 {name}",
      ["getCorridorSurfaces"] = "读取廊道曲面 {name}",
      ["getCorridorTargetMappings"] = "读取廊道目标映射 {corridorName, regionIndex?, baselineIndex?}",
      ["getDrawingInfo"] = "读取当前图纸信息（文件名、单位、对象计数）",
      ["analyzeLayer"] = "图层画像 {layer}：type 分布/块名 Top/文字数字比例/z≠0 占比——判断这层画的是什么，决定过滤条件(types/blockName)",
      ["listDirectory"] = "列目录 {path}：返回子目录+文件名清单(名称/大小，不含内容)——用户给文件夹路径时先调这个看有什么；敏感目录(.git/凭据等)拒绝",
      ["readTextFile"] = "读文本文件 {path, maxLines?, maxBytes?, startLine?}：格式探测(CSV表头/分隔符/列结构)；大文件用 startLine 分页读中段/末尾——内容将发送给模型服务商，敏感文件(config.json/.env/密钥)拒绝",
      ["readDocx"] = "读 Word 文档 {path, maxChars?}：.docx(OOXML) 或 .doc(Word97 老格式) 自动识别，提取正文文本——图纸说明/施工方案类",
      ["readXlsx"] = "读 Excel 表格 {path, maxRows?}：.xlsx 或 .xls(Excel97 老格式) 自动识别；提取第一个 sheet 为 tab 分隔文本(含共享字符串)——点坐标表/工程量清单类",
      ["readDoc"] = "读 Word 老格式 .doc {path, maxChars?}：Word 97-2003 二进制，自带解析——与 readDocx 等效（按格式选名）",
      ["readXls"] = "读 Excel 老格式 .xls {path, maxRows?}：Excel 97-2003 BIFF8 二进制，自带解析——与 readXlsx 等效（按格式选名）",
      ["readPptx"] = "读 PPT 文档 {path, maxChars?}：提取各幻灯片文字",
      ["readZip"] = "读压缩包 {path, entry?}：无 entry=列条目清单(名称/大小)；有 entry=提取该文本条目内容(>1MB/二进制拒绝)",
      ["writeTextFile"] = "写文件到用户指定路径 {path, content?}：用户明确要求生成到某处=授权写（如\"笔记生成到 D盘文件夹\"）；【只新建不覆盖】已有文件(换名或用户删旧)、敏感路径/可执行扩展名禁写、2MB 限制",
      ["getDrawingOverview"] = "图纸总览：单位/图层+数量/块+数量/类型分布/选择集数，涉及图中对象或模糊指令先调 {}",
      ["getDrawingSettings"] = "读取图纸设置（单位、精度等）",
      ["getEntitiesByBlock"] = "按块名列举 ModelSpace 块参照 {blockName, maxCount?}——含插入点坐标",
      ["getEntitiesByLayer"] = "按图层枚举 ModelSpace 实体 {layer, maxCount?, offset?, minZ?, maxZ?}——含坐标，分页取全量；minZ/maxZ 服务端 z 范围过滤（找异常点/筛选，不用拉全量被截断）",
      ["getBlocksByLayer"] = "按图层批量读块引用及属性 {layer, maxCount?, offset?, blockName?, minZ?, maxZ?}——返回每个块的 handle/blockName/坐标/rotation/attributes(tag+text)/块定义内文字。**读高程点/属性数据用它**（getBlockInfo 一次只能读 1 个，大量点必须用本方法分页批量取）",
      ["getEntityInfo"] = "读取单个图元属性（文字/多段线/圆/线/弧/3D 实体/块引用） {handle}",
      ["getFeatureLine"] = "读取特征线 {name}——获取特征线几何与属性",
      ["getGrading"] = "读取放坡信息 {groupName, handle}",
      ["getGradingGroup"] = "读取放坡组信息 {name}",
      ["getGradingGroupVolume"] = "计算放坡体积 {name}",
      ["getIntersection"] = "读取交叉口信息 {name, includeCorridorInfo?, includeCurbReturns?}",
      ["getJobStatus"] = "查询后台任务状态",
      ["getLayers"] = "读取图层列表",
      ["getParcel"] = "读取地块信息 {siteName, parcelName}",
      ["getPipe"] = "读取管道信息 {networkName, pipeName}",
      ["getPipeNetwork"] = "读取管网信息 {name}",
      ["getPipeStructureProperties"] = "读取管/井属性 {networkName, structureName}",
      ["getPressureFittingProperties"] = "读取压力管件属性 {networkName, fittingName}",
      ["getPressureNetworkInfo"] = "读取压力管网信息 {name}",
      ["getPressurePipeProperties"] = "读取压力管道属性 {networkName, pipeName}",
      ["getProfile"] = "读取纵断面信息 {alignmentName, profileName}",
      ["getProfileElevation"] = "读取纵断面高程（同 profileGetElevation） {alignmentName, profileName, station}",
      ["getProjectContext"] = "读取项目上下文信息 {selectedObjectLimit?}",
      ["getSectionData"] = "读取横断面数据 {alignmentName, sampleLineGroupName, station}",
      ["getSelectedCivilObjectsInfo"] = "读取选中 Civil 3D 对象的详细信息 {limit?}",
      ["getSelection"] = "读当前选中集（handles+类型）；先确认是否有选中再动手",
      ["getSelectionDetail"] = "选中集完整几何快照（handle/位置/顶点/文字）——跨图纸重建或分析选中内容用 {}",
      ["getSheetProperties"] = "读取图纸属性 {sheetSetName, sheetName}",
      ["getSheetSetInfo"] = "读取图纸集信息 {name}",
      ["getStructure"] = "读取结构物信息 {networkName, structureName}",
      ["getStyle"] = "读取样式信息 {objectType, styleName}",
      ["getSuperelevation"] = "读取超高数据 {alignmentName, includeRawData?}",
      ["getSurface"] = "读取曲面信息 {name}",
      ["getSurfaceElevation"] = "读取曲面某点高程 {name, x, y}",
      ["getSurfaceElevationsAlong"] = "读取沿线高程 {name, points:[]}",
      ["getSurfaceStatistics"] = "读取曲面统计（高程范围等） {name, analysisType?}",
      ["getSurfaceStatisticsDetailed"] = "读取曲面详细统计 {name}",
      ["getSurfaceVolumeReport"] = "生成曲面体积报告 {baseSurface, comparisonSurface, format?}",
      ["getSurveyFigure"] = "读取测量图形 {name, databaseName?}",
      ["importCogoPoints"] = "导入 Cogo 点 {format, data, targetSurface?}",
      ["importCogoPointsFromFile"] = "文件通道批量导入 Cogo 点 {format, filePath, targetSurface?}——大量点用",
      ["importStm"] = "导入 STM（雨污模型）文件 {filePath?}",
      ["importSurveyLandXml"] = "导入测量 LandXML {filePath, databaseName}",
      ["insertBlock"] = "插入块 {blockName, x, y, scale?, rotation?, layer?}",
      ["interferenceCheck"] = "干涉检查 {handle1, handle2}",
      ["joinEntities"] = "合并图元 {handles:[]}（Line 组合不支持，Polyline 参与即可）",
      ["layerFreeze"] = "冻结图层 {layerName}",
      ["layerIsolate"] = "孤立图层 {handles:[]}（只显示该层）",
      ["layerLock"] = "锁定图层 {layerName}",
      ["layerMatch"] = "图层匹配（改到目标图层） {sourceHandle, targetHandle}",
      ["layerOff"] = "关闭图层 {layerName}",
      ["layerUnlock"] = "解锁图层 {layerName}",
      ["listAlignments"] = "查询路线列表",
      ["listAssemblies"] = "查询装配列表",
      ["listStockSubassemblies"] = "列出 C3D 标准子装配（stock subassembly）类名目录 {category?}——createSubassembly 的 subassemblyType 从这里查；道路结构层常用 BasicLane/LaneSuperelevationAOR/ShoulderExtendAll/DaylightStandard",
      ["importSACSubassembly"] = "导入 SAC 自定义部件 .pkt 文件 {subassemblyName, pktFilePath, insertX?, insertY?, assemblyName?}——用 Subassembly Composer 做的自定义部件（如花岗岩平石/侧石/边石）导入后像标准部件一样加进装配；assemblyName 可选：导入后自动挂到指定装配",
      ["createCustomSubassembly"] = "编程创建自定义子装配 {subassemblyName, points: [{offset,elevation,code?}], links: [{pointIndices:[], code?}], shapes: [{linkIndices:[], code?}], assemblyName?, side?, insertX?, insertY?}——无 .pkt 文件时直接定义断面几何（平石/侧石/边石等）；内部翻译成 SAC XAML 打包导入，几何真生成（probeGeometry 可验证）；返回 handle/pktFilePath",
      ["buildSACSubassembly"] = "AI 生成 SAC 部件 {subassemblyName, xamlContent, categoryName?, description?, atcContent?, paramsXml?, outputPath?}——xamlContent 是 SAC 工作流 XAML（SAC 活动语法），插件自动生成 cfg/emd/pvd 模板并打包成 .pkt，返回 pktFilePath 后接 importSACSubassembly 导入",
      ["listCatchmentGroups"] = "查询汇水区组列表",
      ["listCatchments"] = "查询汇水区列表",
      ["listCivilObjectTypes"] = "列出图纸中的 Civil 3D 对象类型及数量",
      ["listCogoPoints"] = "查询 Cogo 点列表 {groupName?, limit?, offset?}",
      ["listCorridors"] = "查询廊道列表",
      ["listDataShortcuts"] = "查询数据快捷方式列表",
      ["listFeatureLines"] = "查询特征线列表",
      ["listGradingCriteria"] = "列出放坡标准（criteria）",
      ["listGradingGroups"] = "查询放坡组列表",
      ["listGradings"] = "查询放坡列表 {groupName}",
      ["listHydrologyCapabilities"] = "列出水文分析能力清单",
      ["listIntersections"] = "查询交叉口列表 {siteName?}",
      ["listLabelStyles"] = "列出标签样式 {objectType}",
      ["listLabels"] = "列出图纸中的标签对象 {objectType, objectName}",
      ["listMethods"] = "列出所有可用方法清单（支持 filter 参数过滤），先查清单再调用，避免猜方法名",
      ["listParcelSites"] = "查询地块场地（site）列表",
      ["listParcels"] = "查询地块列表 {siteName}",
      ["listPipeNetworks"] = "查询管网列表",
      ["listPipePartsCatalog"] = "列出管道部件目录 {partsList?}",
      ["listPointGroups"] = "查询点组列表",
      ["listPressureNetworks"] = "查询压力管网列表",
      ["listProfiles"] = "查询纵断面列表 {alignmentName}",
      ["listSampleLineGroups"] = "查询采样线组列表 {alignmentName}",
      ["listSectionViews"] = "查询横断面图列表 {alignmentName?, sampleLineGroupName?}",
      ["listSelectedTexts"] = "读取选中文字内容",
      ["listSheetSets"] = "查询图纸集列表",
      ["listSsaCapabilities"] = "列出风暴分析（SSA）能力清单",
      ["listStyles"] = "列出样式清单 {objectType}",
      ["listSurfaces"] = "查询曲面列表",
      ["listSurveyDatabases"] = "查询测量数据库列表",
      ["listSurveyFigures"] = "查询测量图形列表 {databaseName?}",
      ["listSurveyObservations"] = "查询测量观测记录 {databaseName, networkName?, observationType?}",
      ["listTcMethods"] = "列出汇流时间计算方法",
      ["listTexts"] = "读取图纸全部文字 {layer?, maxCount?, offset?}——layer 子串过滤+分页",
      ["loftSolid"] = "放样成实体 {crossSections:[截面handle...] ≥2, guides?:[引导线], path?:路径, ruled?/closed?/draftStart?/draftEnd?(度), thickness?=1, bothSides?, keepProfiles?}——⚠️ 薄壳实体非实心(LoftedSurface+Thicken 链路), 实心需 LOFT 命令兜底; 同步返回 solidHandle",
      ["createNurbsSurface"] = "创建NURBS自由曲面 {uCount,vCount, points:[[x,y,z]...] 共 uCount*vCount 个按 u 方向逐行排列, uDegree?/vDegree?=3, weights?}——返回 handle",
      ["editNurbsControlPoints"] = "编辑NURBS曲面控制点 {handle, points?:[[u,v,x,y,z]绝对], moves?:[[u,v,dx,dy,dz]相对]}",
      ["thickenSurface"] = "曲面加厚成实体 {handle, thickness>0, bothSides?}——返回 solidHandle",
      ["measureArea"] = "测量面积（型带公式）{handle}",
      ["measureDist"] = "测量距离 {x1, y1, x2, y2, z1?, z2?}",
      ["mirror3d"] = "三维镜像 {handle, p1x, p1y, p1z, p2x, p2y, p2z}（镜像轴两点, XY 平面内）",
      ["mirrorEntities"] = "批量镜像 {handles:[]}（以选中集包围盒中心为镜像轴）",
      ["mirrorEntity"] = "镜像单个图元 {handle}",
      ["move3d"] = "三维移动 {handle, dx, dy, dz}",
      ["moveEntities"] = "批量移动 {handles:[], dx, dy, dz?}",
      ["moveEntity"] = "移动单个图元 {handle, dx, dy}",
      ["newDrawing"] = "新建图纸 {templatePath?}——创建新图纸（可选模板）；在 UI 线程(Idle)执行，需 AutoCAD 空闲",
      ["openDrawing"] = "打开已有图纸 {path, readOnly?}——切换到指定 dwg（当前图有未保存修改会先自动保存）；半自动化多图工作流用",
      ["offsetEntity"] = "偏移图元 {handle, distance, layer?}",
      ["openStormSanitaryAnalysis"] = "打开风暴/雨污分析模块 {}",
      ["overkillEntities"] = "清理重复图元 {handles:[]}",
      ["planProductionPublishWorkflow"] = "图纸生产发布向导（多步）",
      ["profileAddCurve"] = "纵断面添加竖曲线 {alignmentName, passThroughX, passThroughY, radius}",
      ["profileAddPvi"] = "纵断面添加 PVI（变坡点） {alignmentName, profileName, station, elevation}",
      ["profileCheckKValues"] = "纵断面竖曲线 K 值检查 {alignmentName, profileName, designSpeed}",
      ["profileDeletePvi"] = "纵断面删除 PVI {alignmentName, profileName, station}",
      ["profileGetElevation"] = "读取纵断面某桩号高程 {}",
      ["profileSetGrade"] = "设置纵断面坡度 {alignmentName, profileName, entityIndex, grade}",
      ["profileViewBandSet"] = "设置纵断面图框带（band set） {profileViewName, bandSetName}",
      ["profileViewCreate"] = "创建纵断面图框 {alignmentName, profileViewName, insertX?, insertY?, style?, bandSet?}——位置可不传（默认路线起点）",
      ["projectReferenceSetupWorkflow"] = "项目参考设置向导（多步）",
      ["projectStartupWorkflow"] = "项目启动向导（多步初始化）",
      ["promoteDataShortcut"] = "提升数据快捷方式（转为本地对象） {shortcutName, shortcutType, newName?}",
      ["publishSheetPdf"] = "发布图纸集为 PDF {outputPath, overwrite?}",
      ["qcCheckAlignment"] = "路线质检 {name, designSpeed?, checkTangents?, checkCurves?, checkSpirals?}——检查路线几何/标准符合性",
      ["qcCheckCorridor"] = "廊道质检 {name}——检查廊道构建/代码集",
      ["qcCheckDrawingStandards"] = "图纸标准检查 {layerPrefix?, checkLineweights?, checkColors?}",
      ["qcCheckLabels"] = "标签质检——检查图纸标签样式/标准符合性 {objectType?, checkMissing?, checkStyleViolations?}",
      ["qcCheckPipeNetwork"] = "管网质检 {name, minCover?, maxSlope?, minSlope?, minVelocity?, maxVelocity?}——检查管网连接/坡度/部件",
      ["qcCheckProfile"] = "纵断面质检 {alignmentName, profileName, maxGrade?, minKValue?}——检查纵断设计标准",
      ["qcCheckSurface"] = "曲面质检 {name, spikeThreshold?, flatTriangleThreshold?}——检查曲面数据/边界/标准",
      ["qcFixAndVerifyWorkflow"] = "质检修复+验证向导（多步）",
      ["qcFixDrawingStandards"] = "修复图纸标准问题 {layerPrefix?, fixSpaces?, maxNameLength?, colorIndex?, lineweight?, dryRun?}",
      ["qcReportGenerate"] = "生成质检报告 {outputPath, overwrite?, includeAlignments?, includeProfiles?, includeCorridors?, includePipeNetworks?, includeSurfaces?, includeLabels?, includeDrawingStandards?}",
      ["qtyAlignmentLengths"] = "计算路线长度（工程量） {names:[], startStation?, endStation?}",
      ["qtyCorridorVolumes"] = "计算廊道体积（工程量） {name}",
      ["qtyEarthworkSummary"] = "土方量汇总——计算并汇总挖填方量 {baseSurface, designSurface, startStation?, endStation?, alignmentName?}",
      ["qtyExportToCsv"] = "导出工程量 CSV {outputPath, filterNames:[], overwrite?, includeAlignments?, includeSurfaces?, includePipeNetworks?, includeParcelAreas?, includePointGroups?}",
      ["qtyMaterialListGet"] = "获取材料清单 {corridorName}",
      ["qtyParcelAreas"] = "计算地块面积 {parcelNames:[], siteName?}",
      ["qtyPipeNetworkLengths"] = "统计管网长度 {name, groupBySize?, groupByMaterial?}",
      ["qtyPointCountByGroup"] = "统计点组内点数 {groupNames:[]}",
      ["qtyPressureNetworkLengths"] = "统计压力管网长度 {name, groupBySize?, groupByMaterial?}",
      ["qtySurfaceVolume"] = "计算曲面体积（工程量） {baseSurface, comparisonSurface, corridorName?}",
      ["rebuildCorridor"] = "重建廊道 {name}",
      ["redoDrawing"] = "重做被撤销的操作 {steps?}",
      ["referenceDataShortcut"] = "引用数据快捷方式 {projectFolder, shortcutName, shortcutType, layer?}",
      ["renderScene"] = "渲染当前视图场景 {}",
      ["renameLayer"] = "重命名图层 {name, newName}",
      ["deleteLayer"] = "删除图层 {name}（0/Defpoints 受保护）",
      ["renameSurface"] = "重命名曲面 {name, newName}",

      ["reportParcels"] = "生成地块报告 {siteName, parcelNames:[], outputPath?, includeCoordinates?, units?, overwrite?}",
      ["resizePipeInNetwork"] = "调整管网中管道尺寸 {networkName, pipeName, newPartName?, newDiameter?}",
      ["resizePressurePipe"] = "调整压力管道尺寸 {networkName, pipeName, newPartName, newDiameter?}",
      ["revolveSolid"] = "旋转成实体 {handle, axisX1, axisY1, axisX2, axisY2, angle}（轴=两点坐标定义，不能穿过 profile；angle 为度）",
      ["rotate3d"] = "三维旋转 {handle, ax, ay, az, bx, by, bz, angle}（轴两点+角度, 度）",
      ["rotateEntities"] = "批量旋转 {handles:[], angle, cx?, cy?}",
      ["rotateEntity"] = "旋转单个图元 {handle, angle, cx?, cy?}",
      ["runLisp"] = "投递 LISP 表达式执行（操作类脚本，无返回值通道；查询类用专用方法） {lisp}",
      ["runoffDetentionWorkflow"] = "径流调蓄向导（多步）",
      ["runoffPipeWorkflow"] = "径流管道向导（多步）",
      ["sampleProfileElevations"] = "采样纵断面高程 {alignmentName, profileName, interval, startStation?, endStation?}",
      ["sampleSurfaceElevations"] = "采样曲面高程（沿路线/多点） {name, method, gridSpacing, boundary:[], points:[], numSamples?}",
      ["saveDrawing"] = "保存当前图纸 {overwrite?, saveAs?}",
      ["saveSelection"] = "捕获当前 CAD 选择集写入快照（面板发送时自动调用） {}",
      ["scaleEntities"] = "批量缩放 {handles:[], factor, cx?, cy?}",
      ["scaleEntity"] = "缩放单个图元 {handle, factor, cx?, cy?}",
      ["scaleText"] = "缩放文字 {handles:[], scaleFactor}",
      ["sectionPlane"] = "创建截面平面 {handle}",
      ["selectByCriteria"] = "按条件选中 {layer?|layers?:[多图层数组/逗号分隔]|type?|types?:[多类型数组/逗号分隔]|blockName?|color?}，真正设置 CAD 选择集并同步快照",
      ["selectEntities"] = "按条件选中图元（参数同 selectByCriteria） {}",
      ["setCatchmentProperties"] = "设置汇水区属性 {catchmentName, runoffCoefficient?, manningsCoefficient?, curveNumber?, description?, newName?}",
      ["setCorridorTargetMappings"] = "设置廊道目标映射 {corridorName, targets:[], regionIndex?, baselineIndex?}",
      ["setEntitiesColor"] = "批量改色 {handles:[], color}",
      ["setEntityLayer"] = "图元归层 {handles:[], layer}——把图元放到指定图层",
      ["setEntityLinetype"] = "设置图元线型 {handles:[], linetype}——线型名如 DASHED/CENTER 或 ByLayer",
      ["setEntityLineweight"] = "设置图元线宽 {handles:[], lineweight}——AutoCAD 线宽枚举值(如 50=0.5mm, -1=ByLayer)",
      ["setEntityTransparency"] = "设置图元透明度 {handles:[], transparency}——0-100 百分比(0=不透明,100=全透明)",
      ["setLayerColor"] = "设置图层颜色 {layer, color}——ACI 颜色号",
      ["setLayerLinetype"] = "设置图层线型 {layer, linetype}——线型名如 DASHED/CENTER",
      ["setLayerLineweight"] = "设置图层线宽 {layer, lineweight}——AutoCAD 线宽枚举值(如 50=0.5mm)",
      ["setLayerTransparency"] = "设置图层透明度 {layer, transparency}——0-100 百分比(0=不透明,100=全透明)",
      ["setEntityColor"] = "修改单个图元颜色 {handle, color}",
      ["setPressureNetworkCover"] = "设置压力管网埋深/覆盖 {networkName, minCoverDepth, maxCoverDepth?}",
      ["setSheetTitleBlock"] = "设置标题栏 {sheetName, titleBlockPath, sheetSetName}——设置图纸标题栏",
      ["setSheetViewScale"] = "设置图纸视图比例 {layoutName, scale, viewportHandle?}",
      ["setSuperelevation"] = "设置超高 {alignmentName, designSpeed, normalCrownSlope, attainmentMethod?, pivotPoint?}——设置路线超高参数",
      ["setSurfaceContourInterval"] = "设置曲面等高线间距 {name, minorInterval, majorInterval}",
      ["setAlignmentStyle"] = "修改已有路线样式/标签集 {alignmentName, style?, labelSet?}——style 用 listStyles objectType:'alignment' 查；labelSet 用 listStyles objectType:'alignmentlabelset' 查",
      ["setProfileStyle"] = "修改已有纵断面样式 {alignmentName, profileName, style?}——style 用 listStyles objectType:'profile' 查；标签集只能在创建时指定",
      ["setProfileViewStyle"] = "修改纵断面图框样式/带集 {profileViewName, style?, bandSet?}——中文纵断面改 bandSet 数据带样式；style 用 listStyles objectType:'profileview' 查",
      ["setVisualStyle"] = "设置视觉样式 {style}（xray/线框/隐藏/真实/概念/着色）",
      ["sliceSolid"] = "剖切实体 {handle, p1x, p1y, p2x, p2y, p3x, p3y, keepBoth?}（平面三点）",
      ["startJob"] = "启动后台任务 {operation}",
      ["stretchEntity"] = "拉伸图元 {handle, dx, dy}",
      ["surfaceComparisonReportWorkflow"] = "曲面对比报告向导（多步）",
      ["sweepSolid"] = "扫掠成实体 {profileHandle, pathHandle}（path 需垂直于 profile 平面）",
      ["syncDataShortcuts"] = "同步数据快捷方式",
      ["traceHydrologyFlowPath"] = "追踪汇流路径 {surfaceName, x, y, stepDistance?, maxSteps?}",
      ["transformCogoPoints"] = "转换 Cogo 点坐标 {pointNumbers:[], translateX?, translateY?, translateZ?, rotateRadians?, scaleFactor?, groupName?}",
      ["transformCoordinates"] = "坐标转换（当前坐标系/经纬度等） {fromSystem, toSystem, x, y, z?}",
      ["trimEntity"] = "修剪图元 {cuttingHandle, targetHandle}",
      ["undoDrawing"] = "撤销上一步操作 {steps?}",
      ["updatePlanProfileSheetAlignment"] = "更新平面/纵断图纸中的路线 {sheetSetName, sheetName, alignmentName, profileName?}",
      ["updatePointGroup"] = "更新点组 {name, description?, includeNumbers?, excludeNumbers?, includeDescriptions?}——更新点组成员/查询条件",
      ["updateSectionViewStyles"] = "更新横断面图样式 {alignmentName, sampleLineGroupName, style?, bandSetStyle?, applyToAll?}",
      ["validatePressureNetwork"] = "验证压力管网 {networkName}",
      ["watershedRunoffWorkflow"] = "流域径流向导（多步）",
      ["writeBlock"] = "写块到文件（SaveAs 覆盖被 xref 锁定文件会失败，换新路径） {handle, filePath}",
    };
    return Task.FromResult<object?>(new Dictionary<string, object?>
    {
      ["count"] = sorted.Count,
      ["methods"] = sorted,
      ["descriptions"] = descriptions,
    });
  }
}
